### ISSUE TITLE
Add "free private repos" to the table

### ISSUE THREAD

**Issue by dbohdan** [helb/helb.github.io#11]
Nice table! As part of my cheering for Chisel (not affiliated but I quite like it and the current owner's other work) I want to note that it offers you free unlimited private repos. BitBucket offers free private repos as well with the limitation that each repo can have up to five collaborators. UX-wise, I suppose you could communicate the limitations for each provider, if any, with a footnote and/or a yellow circle for "partial support".

**Comment by helb** [comment]
Good idea, thanks. I am quite busy right now, but will look into it.

**Comment by dbohdan** [comment]
Great. On an unrelated note, you should emphasise that the project takeovers were _not_ isolated incidents and that SourceForge's response on the matter was that "yes, we may take over an inactive project and mirror its new releases from elsewhere -- even with adware installers". Without such emphasis I assumed that the post at https://sourceforge.net/blog/gimp-win-project-wasnt-hijacked-just-abandoned/ would contain an apologetic press release. A person with whom I shared a link to http://helb.github.io/goodbye-sourceforge/ also skipped reading the SourceForge post for similar reasons.

Edit: clarified which link.
