### ISSUE TITLE
Make 'feature list' easier to read

### ISSUE THREAD

**Issue by Neui** [helb/helb.github.io#32]
In my opinion, the 'feature list' in the table _<sub>(git, mercurial, subversion etc.)</sub>_ are a bit hard to read without rotating your head. I suggest like rotateing them on a 45° angle.
Sample image: _(image magic used, not real)_
![Sample image - The feature list is just rotated on a 45 angle](https://i.imgur.com/9VYU6Vq.png)
That way it is more readable _<sub>for me</sub>_.

**Comment by helb** [comment]
yeah that's probably better, thanks :+1:
